- app/controllers/expanded_questions_controller.rb
- app/controllers/feedbacks_controller.rb
- app/controllers/ideas_controller.rb
- app/controllers/initial_questions_controller.rb
- app/controllers/posts_controller.rb
- app/controllers/replies_controller.rb
- test/controllers/expanded_questions_controller_test.rb
- test/controllers/feedbacks_controller_test.rb
- test/controllers/ideas_controller_test.rb
- test/controllers/initial_questions_controller_test.rb
- test/controllers/posts_controller_test.rb
- test/controllers/replies_controller_test.rb
- InitialQuestions
- ExpandedQuestions
- Ideas
- Posts
- Feedbacks
- Replies
> Empty controllers

- app/models/expanded_question.rb
- app/models/initial_question.rb
- app/models/user.rb
- db/migrate/20250311115235_create_initial_questions.rb
- db/migrate/20250311115445_create_expanded_questions.rb
- db/schema.rb
- test/models/expanded_question_test.rb
- test/models/initial_question_test.rb
I added the has many to the user model, and basic validations to both of the questions models
> Questions models (initial questions and expanded questions) 

- app/controllers/posts_controller.rb
- app/views/posts/_index.html.erb
- app/views/posts/index.html.erb
- config/routes.rb
- db/schema.rb
created action in controller, route, view page and basic iteration, all working
> Posts index action routes skeleton

- app/controllers/feedbacks_controller.rb
- app/controllers/posts_controller.rb
- app/javascript/controllers/reset_form_controller.js
- app/models/feedback.rb
- app/views/feedbacks/_feedback.html.erb
- app/views/posts/show.html.erb
- config/routes.rb
All working, will repeat for replies
> Feedback form

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- db/schema.rb
> Home page thursday

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_upvote.scss
- app/views/feedbacks/_feedback.html.erb
- app/views/ideas/index.html.erb
- app/views/posts/index.html.erb
- app/views/posts/show.html.erb
- app/views/replies/_reply.html.erb
- Unified use of upvote block across all pages and refactored stylesheet
- set position on ideas index card
- increased size of button and count
- added static modifier and disabled button on ideas index card
> Upvote icon styling

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_upvote.scss
- app/controllers/posts_controller.rb
- app/javascript/controllers/form_filter_controller.js
- app/javascript/controllers/section_remove_controller.js
- app/models/post.rb
- app/views/feedbacks/_feedback.html.erb
- app/views/ideas/index.html.erb
- app/views/posts/index.html.erb
- app/views/posts/new.html.erb
- app/views/posts/show.html.erb
- app/views/replies/_reply.html.erb
- config/routes.rb
Using cloudinary, users can (optionally) add an image for their post in the post new page.
Button styling (need some changes after to show confirmation of upload, but working now.
Posts show shows image if one exists
> User added post image

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/initial_questions/new.html.erb
> Generator form/layout improvements

- app/assets/stylesheets/components/_forms.scss
- app/controllers/ideas_controller.rb
- app/views/ideas/edit.html.erb
Fixed the problem when the document is not saved before creating a new post from the idea.
Also I've added some CSS to show description for the buttons when they are hovered:
> Fix form buttons on ideas edit

- app/controllers/initial_questions_controller.rb
- app/models/initial_question.rb
- app/models/user.rb
The format is now consistent every time for the initial AI output. Changed the format the AI is outputting its response to instead be a json object and accessing the keys through parsing.
> Re-generate logic fix

- app/assets/stylesheets/components/_cards.scss
This is how it currently looks on my machine: (strongly recommend to checkout branch locally and check how it looks)
I will merge this after the font changes are merged into master.
> Increase the size of the cards on Ideas#index view page

- app/assets/stylesheets/components/_post_index_card.scss
- app/assets/stylesheets/components/_tags.scss
- app/views/posts/index.html.erb
added tags to post feed cards
removed active class from tags as won’t be used
> posts-feed/add-tags-to-cards

- app/views/pages/home.html.erb
- config/routes.rb
NOTE: All users root to landing page when they login. This needs changing in time, but I'm not sure what we want to change it to.
SIDE NOTE: Did we want to open up parts of the site to logged-out users (such as posts)?
> Landing page routes

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_modal.scss
- app/assets/stylesheets/pages/_initial_questions_show.scss
- app/javascript/controllers/flip_controller.js
- app/javascript/controllers/initial_questions_sidebar_controller.js
- app/views/initial_questions/show.html.erb
Media queries not done yet. Happy to not merge until these are done, but I've had enough of this for one day, sorry
Apologies for the huge commits, I got so lost with this. 
.card-container & .ideas-card no longer in use, but didnt want to delete in case they are being used elsewhere
> Generated ideas/card animations

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_forms.scss
- app/views/initial_questions/new.html.erb
This is how it is going to look at 1440 x 900:
> Generator form css

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_feedback.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_post_index_card.scss
- app/assets/stylesheets/components/_post_show_card.scss
- app/assets/stylesheets/components/_tags.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_post_show.scss
- app/views/feedbacks/_feedback.html.erb
- app/views/posts/new.html.erb
- app/views/posts/show.html.erb
- app/views/replies/_reply.html.erb
Big PR with lots of little changes, should all be detailed in commit messages, feel free to check it out visually on local before merging
> Back half style changes

- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_post_show_card.scss
- app/assets/stylesheets/components/_tags.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/views/ideas/edit.html.erb
- app/views/posts/new.html.erb
- app/views/posts/show.html.erb
Major style changes to posts show, new, and idea edit pages.
Have attempted to create more space in all of them and keep them uniform
> Lot of style fixes

- app/assets/stylesheets/components/_cards.scss
- app/assets/stylesheets/components/_modal.scss
- app/assets/stylesheets/components/_post_index_card.scss
- app/assets/stylesheets/components/_tags.scss
- app/views/ideas/index.html.erb
- app/views/initial_questions/show.html.erb
- app/views/posts/_posts.html.erb
- app/views/posts/new.html.erb
- app/views/posts/show.html.erb
Fixed generated ideas cards - janky as hell but looks good on my laptop full screen
Reduced border on gen ideas and my idea cards
Left align title and tagline on idea cards and added lightbulb emoji
Unified taglines across all pages, italicised with quotation marks
> Cards and tagline styling

- app/assets/stylesheets/components/_feedback.scss
- app/assets/stylesheets/components/_post_index_card.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_post_show.scss
updated placeholder text to lighter colour on all form
also increased size of titles on post index cards
> Placeholder changes

- app/assets/stylesheets/components/_cards.scss
- app/javascript/controllers/initial_questions_sidebar_controller.js
- app/views/initial_questions/show.html.erb
- db/schema.rb
screenshots to show changes to styling (fixed height and width of cards can be changed if its too big)
> Show page styling
